MitraKaryaSystem/Controllers/ProductController.cs
using API.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MitraKaryaSystem.Models;
namespace MitraKaryaSystem.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductService _service;
        private readonly ICategoryService _categoryService;
        private readonly IUnitService _unitService;
        private readonly ISupplierService _supplierService;
        public ProductController(IProductService service, ICategoryService categoryService, IUnitService unitService, ISupplierService supplierService)
        {
            _service = service;
            _categoryService = categoryService;
            _unitService = unitService;
            _supplierService = supplierService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Form(int id)
        {
            var data = new ProductViewModel();
            if (id != 0)
            {
                data.ProductModel = await _service.FillFormProduct(id);
                return View(data);
            }
            return View(data);
        }
        public async Task<object> GetProductList()
        {
            return await _service.GetProductList();
        }
        public async Task<object> GetCategoryList()
        {
            return await _categoryService.GetCategoryList();
        }
        public async Task<object> GetSupplierList()
        {
            return await _supplierService.GetSupplierList();
        }
        public async Task<object> GetUnitList()
        {
            return await _unitService.GetUnitList();
        }
        public async Task<JsonResult> SaveProduct(ProductViewModel product)
        {
            return Json(await _service.SaveProduct(product.ProductModel));
        }
        public async Task<JsonResult> SaveCategory(CategoryModel category)
        {
            return Json(await _categoryService.SaveCategory(category));
        }
        public async Task<JsonResult> SaveUnit(UnitModel unit)
        {
            return Json(await _unitService.SaveUnit(unit));
        }
        public async Task<JsonResult> DeleteProduct(int id)
        {
            return Json(await _service.DeleteProduct(id));
        }
        public async Task<JsonResult> DeleteCategory(int id)
        {
            return Json(await _categoryService.DeleteCategory(id));
        }
        public async Task<JsonResult> DeleteUnit(int id)
        {
            return Json(await _unitService.DeleteUnit(id));
        }
        public async Task<IActionResult> FillFormCategory(int id)
        {
            return PartialView("_TableCategory", await _categoryService.FillFormCategory(id));
        }
        public async Task<IActionResult> FillFormUnit(int id)
        {
            return PartialView("_TableUnit", await _unitService.FillFormUnit(id));
        }

        public async Task<JsonResult> GetProductComboList()
        {
            return Json(await _service.GetProductComboList());
        }
        public async Task<IActionResult> FillFormProduct(int id)
        {
            try
            {
                var data = await _service.FillFormProduct(id);
                var viewModel = new ProductViewModel
                {
                    ProductModel = data
                };
                return PartialView("Form", viewModel); // Return the "Form" view with the filled data
            }
            catch (Exception ex)
            {
                // Handle the exception, you might want to log it or return an error view
                return View("Error");
            }
        }
    }
}

MitraKaryaSystem/Controllers/RoleController.cs
using API.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MitraKaryaSystem.Models;

namespace MitraKaryaSystem.Controllers
{
    [Authorize]
    public class RoleController : Controller
    {
        private readonly IRoleService _roleService;

        public RoleController(IRoleService roleService)
        {
            _roleService = roleService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Route("FillGridRole")]
        public async Task<JsonResult> FillGridRole()
        {
            return Json(await _roleService.GetRoleList());
        }
        [HttpPost]
        [Route("SaveRole")]
        public async Task<IActionResult> SaveRole([FromBody] RoleViewModel request)
        {
            return Json(await _roleService.SaveRole(request));
        }

        [Route("FillFormRole")]
        [HttpPost]
        public async Task<IActionResult> FillFormRole(int id)
        {
            return PartialView("_RoleModal", await _roleService.FillFormRole(id));
        }

        [Route("DeleteRole")]
        [HttpPost]
        public async Task<IActionResult> DeleteRole(int id)
        {
            return Json(_roleService.DeleteRole(id));
        }
    }
}

MitraKaryaSystem/Controllers/StockInController.cs
using API.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using MitraKaryaSystem.Models;

namespace MitraKaryaSystem.Controllers
{
    public class StockInController : Controller
    {
        private readonly IStockInService _stockInService;

        public StockInController(IStockInService stockInService)
        {
            _stockInService = stockInService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> ScanBarcode(string barcode)
        {
            return Json(await _stockInService.ScanBarcode(barcode));
        }
        public async Task<IActionResult> FillFormProduct(int id)
        {
            try
            {
                return PartialView("_FormDetail", await _stockInService.FillFormDetail(id)); // Return the "Form" view with the filled data
            }
            catch (Exception e)
            {
                return Json(new { success = false, error = e.Message });
            }
        }

        public async Task<IActionResult> FillForm(int id)
        {
            try
            {
                return PartialView("_FormHeader", await _stockInService.FillForm(id));
            }
            catch (Exception e)
            {
                return Json(new { success = false, error = e.Message });
            }
        }
        [HttpPost]
        public async Task<JsonResult> Save(StockInModel stockIn)
        {
            try
            {
                return Json(await _stockInService.Save(stockIn));
            }
            catch (Exception e)
            {
                return Json(new { success = false, error = e.Message });
            }
        }
        public async Task<JsonResult> GetDetailListById(int id)
        {
            return Json(await _stockInService.GetDetailListById(id));
        }
        public async Task<object> GetTradeList()
        {
            return Json(await _stockInService.GetTradeList());
        }
        public async Task<object> DeleteItem(int id)
        {
            return Json(await _stockInService.DeleteProductById(id));
        }
        public async Task<object> Delete(int id)
        {
            return Json(await _stockInService.DeleteById(id));
        }
    }
}

MitraKaryaSystem/Controllers/UserController.cs
using API.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MitraKaryaSystem.Models;

namespace MitraKaryaSystem.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService service)
        {
            _userService = service;
        }

        public IActionResult Index()
        {
            return View();
        }
        [Route("GetUserList")]
        public async Task<JsonResult> GetUserList()
        {
            return Json(await _userService.GetUserList());
        }
        [Route("SaveUser")]
        [HttpPost]
        public async Task<JsonResult> SaveUser(UserModel user)
        {
            return Json(await _userService.SaveUser(user));
        }

        [Route("FillForm")]
        [HttpPost]
        public async Task<IActionResult> FillForm(int id)
        {
            return PartialView("_UserModal", await _userService.FillForm(id));
        }

        [Route("DeleteUser")]
        [HttpPost]
        public async Task<JsonResult> DeleteUser(int id)
        {
            return Json(await _userService.DeleteUser(id));
        }
    }
}

MitraKaryaSystem/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    Mitra Karya System - 2024
    <div class="float-right d-none d-sm-inline-block">
        <b>Version 1.0</b>
    </div>
</footer>

MitraKaryaSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
    <link href="https://cdn.datatables.net/v/bs5/dt-1.13.7/r-2.5.0/sl-1.7.0/datatables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css">
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <style>
        .asterisk {
            color: red;
            margin-left: 3px;
        }
    </style>
</head>
<body class="hold-transition sidebar-mini  sidebar-collapse layout-footer-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-light-primary navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <partial name="_LoginPartial" />

                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-light-primary" style=" background-color:skyblue" elevation-4">
            <a asp-action="Index" asp-controller="Home" class="navbar-brand brand-link">
                <img src="~/dist/img/AdminLTELogo.png" class="brand-image img-circle elevation-2">
                <span class="brand-text font-weight-light">@ViewData["Title"]</span>
            </a>
            <partial name="_SideBar" />

        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- /.content-header -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <!-- Main content -->
                        <section class="content">
                            <div class="container-fluid">
                                @RenderBody()
                            </div><!--/. container-fluid -->
                        </section>
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- Main Footer -->
        <partial name="_Footer" />
    </div>


    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/v/bs5/dt-1.13.7/r-2.5.0/sl-1.7.0/datatables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/dist/js/adminlte.js"></script>
    <!-- AdminLTE -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MitraKaryaSystem/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - MitraKaryaSystem</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/MitraKaryaSystem.styles.css" asp-append-version="true" />
</head>
<body>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - Mitra Karya System
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MitraKaryaSystem/Views/Shared/_SideBar.cshtml
            <!-- Sidebar -->
<div class="sidebar">
    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item">
                <a asp-action="Index" asp-controller="User" class="nav-link">
                    <i class="fa-solid fa-users"></i>
                    <p>
                        User
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="Index" asp-controller="Role" class="nav-link">
                    <i class="fa-solid fa-user-gear"></i>
                    <p>
                        Role
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="Index" asp-controller="Customer" class="nav-link">
                    <i class="fa-solid fa-user-gear"></i>
                    <p>
                        Customer
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="Index" asp-controller="Product" class="nav-link">
                    <i class="fa-solid fa-user-gear"></i>
                    <p>
                        Product
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="Index" asp-controller="StockIn" class="nav-link">
                    <i class="fa-solid fa-cart-shopping"></i>
                    <p>
                        Stock In
                    </p>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.sidebar-menu -->
</div>
<!-- /.sidebar -->

MitraKaryaSystem/Views/Shared/_StatusList.cshtml
<div class="container-fluid h-100 add-card-setting">
    <div class="row">
        <div class="col">
            <div class="card card-row bg-gradient-primary">
                <div class="card-header">
                    Draft / Revise
                    <div class="card-tools"><i class="far fa-edit"></i></div>
                </div>
                <div class="card-body">
                    <h5 class="card-title">0</h5>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card card-row bg-gradient-success">
                <div class="card-header">
                    In Progress
                    <div class="card-tools"><i class="fa-solid fa-spinner"></i></div>
                </div>
                <div class="card-body">
                    <h5 class="card-title">0</h5>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card card-row bg-gradient-purple">
                <div class="card-header">
                    Validation Task
                    <div class="card-tools"><i class="fa-solid fa-list-check"></i></div>
                </div>
                <div class="card-body">
                    <h5 class="card-title">0</h5>
                </div>
            </div>
        </div>
    </div>
</div>